In [14]:
# Traverse all Elements
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in x:
    for j in i:
        print(j,end=" ")
    print()    

1 2 3 
4 5 6 
7 8 9 


In [26]:
# To specifiy the integer
y=np.zeros((4,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
y=np.zeros((2,3),dtype=np.int32)
y

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [34]:
z=np.ones((3,2),dtype=np.int32)
z

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [36]:
# 2D Matrix Addition 

In [38]:
import numpy as np

In [3]:
import numpy as np

x1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

result = []
for i in range(len(x1)):
    row = []
    for j in range(len(x1[0])):
        row.append(x1[i][j] + x2[i][j])
    result.append(row)  # Corrected indentation

print(result)  # Display the result

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]


In [40]:
# Matrix Multiplication

In [42]:
import numpy as np

In [46]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9,]])
x2=np.array([[10,20,30],[40,50,60],[70,80,90]])
result = np.dot(x1,x2)
print(result)


[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
