In [4]:
# Numpy library
import numpy as py

In [8]:
y= py.array([10,20,30,40,50])
for i in y:
    print(i,end=" ")
    

10 20 30 40 50 

In [40]:
# Accessing elements using numpy library
y= np.array([10,20,30,40,50,])
print(y[0]) #acessing the elements
print(y[1])
print(y[2])
print(y[3])

10
20
30
40


In [11]:
# Insert operation
import numpy as py
y= np.array([10,20,30,40,50,])
z=np.insert(y,2,80)    #(variable name,indexposition, element)
print(z)

[10 20 80 30 40 50]


In [10]:
# Remove operation
import array as arr
x=arr.array('i',[10,20,30,40,50])
x.remove(40) # Remove operation
print(x)

array('i', [10, 20, 30, 50])


In [14]:
# Search operation
import array as arr
x=arr.array('i',[10,20,30,40,50])
print(x.index(20)) # Search operation

1


In [16]:
 # Update Operation
import array as arr
x=arr.array('i',[10,20,30,40,50])
x[0]=100 # Update Operation
print(x)

array('i', [100, 20, 30, 40, 50])


In [20]:
# Finding the largest and Smallest element in the Array
import numpy as np
x=np.array([10,20,30,40,50,60])
def min_max(x):
    min_e=np.min(x)
    max_e=np.max(x)
    return min_e,max_e
result = min_max(x)
print(result)


(10, 60)


In [22]:
# Find the sum and average of an Array element 
import numpy as np
x= np.array([10,20,30,40,50])
def avg(x):
    l=len(x)
    add_all=sum(x)
    average=add_all/l
    return average

result=avg(x)
print(result)

30.0


In [38]:
# Write a function to remove the Duplicate in an Array
# Looping and Membership
import numpy as np
x= np.array([10,20,30,40,50,20])
def r_dup(x):
    new_arr=[]
    for i in x:
        if i not in new_arr:
            new_arr.append(i)
    return np.array(new_arr)    
    
result=r_dup(x)
type(result)
print(result)

[10 20 30 40 50]


In [10]:
# Removing Duplicate Elementa in Array
import numpy as np

x = np.array([10, 20, 30, 40, 50, 10, 0, 30, 100])

def r_dup(x):
    return np.unique(x)  # More efficient and preserves NumPy array properties

result = r_dup(x)
print(result)


[  0  10  20  30  40  50 100]


In [4]:
# Reversing an Array
import numpy as np

x = np.array([10, 20, 30, 40, 50, 10, 0, 30, 100])
print(x[::-1]) # Slicing Method


[100  30   0  10  50  40  30  20  10]


In [30]:
# Find the index of an Element using Exception

import numpy as np

x = np.array([10, 20, 30, 40, 50])
def i_ele(x,s_ele):
    try:
        n=len(x)
        for i in range(n):
            if x[i]== s_ele:
                return i
        raise ValueError("Element not found")
    except ValueError:
        return -1
s_ele=int(input())
result = i_ele(x,s_ele)
print("Aladsu",result)


 20


Aladsu 1


In [46]:
# Array special prouct without division 
import numpy as np

x = np.array([1, 2, 3, 4, 5])
def pro_ExceptSelf(x):
    n=len(x)
    res=[1]*n
    for i in range(n):
        for j in range(n):
            if i !=j:
                res[i]*=x[j]
    return res
result = pro_ExceptSelf(x)
print("Product array ",result)

Product array  [120, 60, 40, 30, 24]


In [56]:
# Array special prouct without division 
import numpy as np
import math

x = np.array([1, 2, 3, 4, 5])
def pro_ExceptSelf_div(x):
    total_product=math.prod(x)
    prod_arr =[]
    for i in x:
        prod_arr.append(total_product//i)
    return prod_arr
print("Original array: ",x)
result=pro_ExceptSelf_div(x)
print("Product array: ",result)      

Original array:  [1 2 3 4 5]
Product array:  [120, 60, 40, 30, 24]


In [2]:
# Last One Occurance 
import numpy as np
x=np.array([0,1,1,0,1,0,1,0,0])
def last1_occur(x):
    index=-1
    n=len(x)
    for i in range(n):
        if x[i]==1:
            index=i
    return index
print("last index of one:",last1_occur(x))

last index of one: 6


In [ ]:
# Move all Zeros to End
import numpy as np
x=np.array([1,1,1,1,0,0,0])
def move_zero_end(x):
    count_0=0
    store_1=0
    for i in x:
        if i==1:
            store_1+=1
        else:
            count_0+=1
    result =([1]+store_1)+([0]+count_0)
    return result
print("output:",move_zero_end(x))

In [7]:
# Move all Zeros to End
import numpy as np
x = np.array([0, 1, 0, 1, 0, 1, 1, 1])
def Move_Zero_end(x):
    Count_0 = 0
    Store_1 = 0
    i = len(x)-1
    while i >= 0:
        if x[i] == 1:
            Store_1 += 1
        else:
            Count_0 += 1
        i -= 1
    result = [1] * Store_1 + [0] * Count_0
    return result
print("output:", Move_Zero_end(x))

output: [1, 1, 1, 1, 1, 0, 0, 0]


In [9]:
# Binary Array Sorting
import numpy as np
x = np.array([1,2,3,4,5,6])
y= np.array([4,5,6,7,8])
def arr_common(x,y):
    common=[]
    for i in x:
        if i in y and i not in common:
            common.append(i)
    return np.array(common)
print(" Common Elements : ",arr_common(x,y))    


 Common Elements :  [4 5 6]
